/**
 * Pre-build clean step.
 *
 * Because `vite.config.ts` uses `outDir: '.'` (project root) for direct
 * deployment, build artifacts share the same directory as source files.
 * This script:
 *   1. Removes previous build artifacts so each `vite build` starts clean:
 *      - `/assets/` (hashed JS / CSS chunks)
 *      - per-route folders generated by the prerender (about/, marketing/...)
 *   2. Restores the SPA entry `index.html` from `index.html.template` so
 *      Vite always reads a clean, hash-free template (the prerender step
 *      overwrites the root `index.html` with the home page output).
 *
 * Source code (`src/`, `public/`, `scripts/`, config files, the template
 * itself) is never touched.
 */

import { copyFileSync, existsSync, rmSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const ROOT = path.resolve(path.dirname(__filename), '..')

/** Top-level entries that the build / prerender produces. */
const TARGETS = [
  'assets',
  'og',
  'about',
  'contact',
  'privacy-policy',
  'marketing',
  'development',
  'products'
]

let removed = 0
for (const name of TARGETS) {
  const full = path.join(ROOT, name)
  if (existsSync(full)) {
    rmSync(full, { recursive: true, force: true })
    console.log(`[clean]  ✓ removed ${name}`)
    removed += 1
  }
}

const template = path.join(ROOT, 'index.html.template')
const indexHtml = path.join(ROOT, 'index.html')
if (existsSync(template)) {
  copyFileSync(template, indexHtml)
  console.log('[clean]  ✓ restored index.html from index.html.template')
} else {
  console.warn('[clean]  ! index.html.template not found — skipping restore')
}

console.log(`[clean] done. removed=${removed}`)
